package ajedrezgame;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.plaf.basic.BasicOptionPaneUI;

/**
 *
 * @author PC
 */
public class ajedrezgame extends javax.swing.JFrame {
    
    private final JButton[][]boardButtons = new JButton[8][8];
    private final String[][] boardState = {
        { "r", "n", "b", "q", "k", "b", "n", "r" },
        { "p", "p", "p", "p", "p", "p", "p", "p" },
        { "", "", "", "", "", "", "", "" },
        { "", "", "", "", "", "", "", "" },
        { "", "", "", "", "", "", "", "" },
        { "", "", "", "", "", "", "", "" },
        { "P", "P", "P", "P", "P", "P", "P", "P" },
        { "R", "N", "B", "Q", "K", "B", "N", "R" }
    };
    
    private final HashMap<String, String> pieceIcons = new HashMap<>() {{
        put("R", "♖"); put("N", "♘"); put("B", "♗"); put("Q", "♕"); put("K", "♔"); put("P", "♙");
        put("r", "♜"); put("n", "♞"); put("b", "♝"); put("q", "♛"); put("k", "♚"); put("p", "♟");
        put("", "");
    }};
    
    private JButton selectedButton = null;
    private int selectedRow, selectedCol;

    /**
     * Creates new form ajedrezgame
     */
    public ajedrezgame() {
        setTitle ("Chess Game");
        setSize(800,800);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new GridLayout(8,8));
        initializeBoard();
        setVisible(true);
    }
    private void initializeBoard(){
        for (int row = 0; row < 8; row++){
            for (int col = 0; col < 8; col++){
                JButton button = new JButton(pieceIcons.get(boardState[row][col]));
                button.setFont(new Font("SansSerif",Font.PLAIN,44));
                button.setBackground((row + col) % 2 == 0 ? Color.WHITE : Color.GRAY);
                button.putClientProperty("row", row);
                button.putClientProperty("col", col);
                button.addActionListener(new ButtonClickListener());
                boardButtons[row][col]=button;
                add(button);
            }
        }
    }
    private class ButtonClickListener implements ActionListener{
        @Override
            public void actionPerformed(ActionEvent e) {
                JButton clickedButton = (JButton) e.getSource();
                int row= (int) clickedButton.getClientProperty("row");
                int col= (int) clickedButton.getClientProperty("col");
                
                if (selectedButton == null && !boardState[row][col].equals("")){
                    selectedButton = clickedButton;
                    selectedRow = row;
                    selectedCol = col;
                    clickedButton.setBackground(Color.DARK_GRAY);
                } else if (selectedButton !=null) {
                    boardState[row][col] = boardState[selectedRow][selectedCol];
                    boardState[selectedRow][selectedCol]="";
                    boardButtons[selectedRow][selectedCol].setText("");
                    boardButtons[row][col].setText(pieceIcons.get(boardState[row][col]));
                    boardButtons[selectedRow][selectedCol].setBackground((selectedRow + selectedCol)%2==0 ? Color.WHITE: Color.GRAY);
                    selectedButton = null;
                }
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajedrezgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajedrezgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajedrezgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajedrezgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajedrezgame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
